### ISSUE TITLE
FOD: delay between HBM and actually dimming by SystemUI

### ISSUE THREAD

**Issue by ngxson** [SyberiaProject-Devices/platform_device_xiaomi_laurel_sprout#3]
Hi @HarukeyUA ,

Thanks for your excellent work.

I have a question. Maybe kind of noob. My hypothesis is that the screen flickering issue when using FOD, is due to the race condition between HBM and dimming layer from SystemUI. I know it's not easy to fix, but I think can we add a delay [before applying DISPPARAM_HBM_FOD_ON](https://github.com/SyberiaProject-Devices/platform_device_xiaomi_laurel_sprout/blob/40dcf9746d6656f91483b815337465bbb4b9ebf8/fod/FingerprintInscreen.cpp#L96)?

I know it won't fix the flickering issue, but for now it works that way:
`normal => finger press on the FOD => HBM => (delay) => dimming (SystemUI)`
which is not very good, both for our eyes (seeing a flashing bright light) and the display

By adding a delay, we can see:
```
normal => finger press => (delay) => dimming (SystemUI)
                          (...............delay...............) => HBM
```

Unfortunately, I'm living in a country side. Due to COVID-19, I don't have a good internet access to clone big things from github (even SSH to Google Cloud stucks). Therefore, I have no idea how to build things myself.

**Comment by ngxson** [comment]
Or maybe can we try enabling [FingerprintInscreen::shouldBoostBrightness()](https://github.com/SyberiaProject-Devices/platform_device_xiaomi_laurel_sprout/blob/40dcf9746d6656f91483b815337465bbb4b9ebf8/fod/FingerprintInscreen.cpp#L145) ?

This way, the brightness will be updated just the same time with [FODCircleView.showCircle()](https://github.com/syberia-project/platform_frameworks_base/blob/c44582e4c3c734f53ef12a741a322c8a8f63165d/packages/SystemUI/src/com/android/systemui/biometrics/FODCircleView.java#L312)

**Comment by HarukeyUA** [comment]
High brightness flicker will be fixed after http://gerrit.syberiaos.com/c/syberia-project/platform_frameworks_base/+/4128 merge

**Comment by ngxson** [comment]
That PR has been abandoned. Can we just try enabling FingerprintInscreen::shouldBoostBrightness() ?
